// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCctBJgylKwm_XdGIGUr8K5TtWXve_EHlE',
    appId: '1:650219454971:web:28d4c7690fa16db252cb5e',
    messagingSenderId: '650219454971',
    projectId: 'park-planner-mobile-app',
    authDomain: 'park-planner-mobile-app.firebaseapp.com',
    databaseURL: 'https://park-planner-mobile-app-default-rtdb.firebaseio.com',
    storageBucket: 'park-planner-mobile-app.appspot.com',
    measurementId: 'G-5G7BKHH35C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4ch-AUtWkkGg2oEAj_mBX54BmGAqAju8',
    appId: '1:650219454971:android:31beb5a2771d660852cb5e',
    messagingSenderId: '650219454971',
    projectId: 'park-planner-mobile-app',
    databaseURL: 'https://park-planner-mobile-app-default-rtdb.firebaseio.com',
    storageBucket: 'park-planner-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoEabRZS4HpTzTRajuDS74rIY_f8dJvbg',
    appId: '1:650219454971:ios:5be9dffbd43b573b52cb5e',
    messagingSenderId: '650219454971',
    projectId: 'park-planner-mobile-app',
    databaseURL: 'https://park-planner-mobile-app-default-rtdb.firebaseio.com',
    storageBucket: 'park-planner-mobile-app.appspot.com',
    iosBundleId: 'com.example.accessControlResidential',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoEabRZS4HpTzTRajuDS74rIY_f8dJvbg',
    appId: '1:650219454971:ios:b417f59cf160125252cb5e',
    messagingSenderId: '650219454971',
    projectId: 'park-planner-mobile-app',
    databaseURL: 'https://park-planner-mobile-app-default-rtdb.firebaseio.com',
    storageBucket: 'park-planner-mobile-app.appspot.com',
    iosBundleId: 'com.example.accessControlResidential.RunnerTests',
  );
}
